### ISSUE TITLE
ModuleNotFoundError: No module named 'pythx.config'

### ISSUE THREAD

**Issue by b-mueller** [dmuhs/pythx#3]
* pythx version: Master
* Python version: 3.6.3
* Operating System: Mac OS Mojave
 
### Description

After installing PythX using setup.py, I get a "module not found" error when invoking the CLI.

### What I Did

Installation:

```
$ git clone https://github.com/dmuhs/pythx/
$ cd pythx
$ python setup.py install
```

Error:

```
$ pythx
Traceback (most recent call last):
  File "/Users/bernhardmueller/.pyenv/versions/mythril/bin/pythx", line 11, in <module>
    load_entry_point('pythx==0.1.0', 'console_scripts', 'pythx')()
  File "/Users/bernhardmueller/.pyenv/versions/mythril/lib/python3.6/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/bernhardmueller/.pyenv/versions/mythril/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/Users/bernhardmueller/.pyenv/versions/mythril/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/Users/bernhardmueller/.pyenv/versions/mythril/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/bernhardmueller/.pyenv/versions/mythril/lib/python3.6/site-packages/pythx-0.1.0-py3.6.egg/pythx/__init__.py", line 8, in <module>
    from pythx.config import config
ModuleNotFoundError: No module named 'pythx.config'
(mythril) cerebral-cortex:pythx bernhardmueller$ pythx
Traceback (most recent call last):
  File "/Users/bernhardmueller/.pyenv/versions/mythril/bin/pythx", line 11, in <module>
    load_entry_point('pythx==0.1.0', 'console_scripts', 'pythx')()
  File "/Users/bernhardmueller/.pyenv/versions/mythril/lib/python3.6/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/bernhardmueller/.pyenv/versions/mythril/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/Users/bernhardmueller/.pyenv/versions/mythril/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/Users/bernhardmueller/.pyenv/versions/mythril/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/bernhardmueller/.pyenv/versions/mythril/lib/python3.6/site-packages/pythx-0.1.0-py3.6.egg/pythx/__init__.py", line 8, in <module>
    from pythx.config import config
ModuleNotFoundError: No module named 'pythx.config'
```

**Comment by dmuhs** [comment]
Managed to reproduce it locally. Proposed a fix in #5 with some more explanation. :+1: In any case `pip3 install --user .` or the equivalent on your machine using Python 3 should work fine. There you can also pass in `--editable` to hack on the code and test out the CLI without having to reinstall it.
